//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reductech.EDR.Connectors.StructuredData.Tests.SchemaExamples {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Examples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Examples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reductech.EDR.Connectors.StructuredData.Tests.SchemaExamples.Examples", typeof(Examples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to þDOCIDþþPARENT_DOCIDþþATTACH_DOCIDþþBEGINBATESþþENDBATESþþBEGINGROUPþþENDGROUPþþPAGECOUNTþþITEMPATHþþTEXTPATHþþTIFFPATHþþNameþþTitleþþCustodianþþPath NameþþCreatedþþFile CreatedþþFile AccessedþþFile ModifiedþþItem DateþþTop-level Item DateþþFromþþToþþCcþþBccþþSubjectþþFile TypeþþFile Extension (Original)þþFile Extension (Corrected)þþFile SizeþþGUIDþþParent GUIDþþTop-level GUIDþþMD5 DigestþþOriginal FileþþAppNameþþAuthorþþComment AuthorsþþContains CommentsþþLast Authorþ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadFile {
            get {
                return ResourceManager.GetString("LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;type&quot;: &quot;STATE&quot;,  &quot;value&quot;: {}}
        ///{&quot;type&quot;: &quot;SCHEMA&quot;, &quot;stream&quot;: &quot;pull_requests&quot;, &quot;schema&quot;: {&quot;type&quot;: [&quot;null&quot;, &quot;object&quot;], &quot;selected&quot;: true, &quot;additionalProperties&quot;: false, &quot;properties&quot;: {&quot;_sdc_repository&quot;: {&quot;type&quot;: [&quot;string&quot;]}, &quot;id&quot;: {&quot;type&quot;: [&quot;null&quot;, &quot;string&quot;]}, &quot;url&quot;: {&quot;type&quot;: [&quot;null&quot;, &quot;string&quot;]}, &quot;number&quot;: {&quot;type&quot;: [&quot;null&quot;, &quot;integer&quot;]}, &quot;state&quot;: {&quot;type&quot;: [&quot;null&quot;, &quot;string&quot;]}, &quot;title&quot;: {&quot;type&quot;: [&quot;null&quot;, &quot;string&quot;]}, &quot;body&quot;: {&quot;type&quot;: [&quot;null&quot;, &quot;string&quot;]}, &quot;labels&quot;: {&quot;type&quot;: [&quot;null&quot;, &quot;array&quot;], &quot;items&quot;: {&quot;type&quot;: [&quot;n [rest of string was truncated]&qu....
        /// </summary>
        internal static string SingerData {
            get {
                return ResourceManager.GetString("SingerData", resourceCulture);
            }
        }
    }
}
